### ISSUE TITLE
Instructions copy for 2-2

### ISSUE THREAD

**Issue by caike** [pluralsight-projects/AspNetCore-WishList#16]
# 2-2

From: 

> In the `Configure` method remove the `app.Run` entirely and replace it with a call to UseMvcWithDefaultRoute on app.

to:

> In the `Configure` method, remove the call to `app.Run`. Replace it with a call to `UseMvcWithDefaultRoute` on `app.`

**Comment by caike** [comment]
# 3-2

Suggested copy:

> In the `Configure` method, before `UseMvcWithDefaultRoute`, add a condition that calls `IsDevelopment` on `env` and checks if the value returned is truthy.

> If so, it should call `UseDeveloperExceptionPage` on `app` in order to get better detailed error pages.

> Otherwise, it should call `UseExceptionHandler` on `app` and pass it the argument "/Home/Error". Next, we'll create the generic Error page provided by this method.

**Comment by caike** [comment]
# 3-3

1. Fix typo on `inherit`.
2. Add format to `using` on:

>  (you will need to add a `using` directive for the `Microsoft.AspNetCore.Mvc` namespace)

**Comment by caike** [comment]
# 4-3

1. Add format to `using` on:

> You will need to add a `using` statement for `WishList.Data`

# 4-4

From: 
> This class should contain a `public` property `Description` of type `string`.

To:
> It should also contain a `public` property `Description` of type `string`.

# 4-5

Fix formatting to:

> In the `ApplicationDbContext` class, add a new `public` property `Items` of type `DbSet<Item>`. (Note : You'll need to add a `using` statement for `WishList.Models`)

**Comment by caike** [comment]
# 5-3

1. Fix format

> This view should use a model of `Item.`

2. Something is wrong with the following error message

<img width="732" alt="build_a_wishlist_application_with_asp_net_core___pluralsight_projects" src="https://user-images.githubusercontent.com/10722/40320283-238dbdba-5cf9-11e8-8964-7386bdfececa.png">

**Comment by caike** [comment]
This could be a Brave (browser) only thing, but I'm noticing the arrow icon for the "Watch Answer" is slightly misaligned:

<img width="199" alt="build_a_wishlist_application_with_asp_net_core___pluralsight_projects" src="https://user-images.githubusercontent.com/10722/40321003-a3d77b08-5cfb-11e8-8c7b-aa777537bc65.png">

**Comment by EricJFisher** [comment]
I've made all the fixes for everything except the "Watch Answer" video button, I'm passing that on to Adam and team so they are aware. (I've noticed other weird stuff in different browsers)
