### ISSUE TITLE
Feedback on project

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/AspNetCore-WishList#27]
@EricJFisher 

Nothing critical, but **more important** issues are under [5.4](#5.4) and [6.6](#6.6) (easy one to fix!) below.
<br />
<br />

---

## Build a Wishlist Application with ASP.NET Core Feedback

- *General feedback*
  - have better correspondence name-wise and ideally order-wise 
    - can you have #s in the test name?  use numbers for correspondence and order
    - make it correspond more to name of task
  - was expecting check my work to take 30-60 seconds.  didn't time, but definitely faster that that!  :clap:
  - Really like the code-complete Visual Studio provides, and prop and ctor shortcuts or whatever they're called

Note e.g., 1.6 means task 6 of level 1, where level 1 is *Setup*

- *1.6 Verify Local Envirornment*
  - _file from the directory ~~you~~ where you cloned the project_
- *3.1 Create a Generic Welcome View*
  - _(Note: you should remove any generated HTML from this new view and any other views you create)_  *good!*
- *4.3 Configure EntityFramework*
  - _minor, arguable_.  mention the changes will be in `Startup.cs`

<a name="5.4"></a>
- *5.4 Create The Index View*
  - accepting following is **more important**, but tough, so best to instead tighten up description to require solution matching existing regex
  - should also accept loop variables other than `item` <br />
  ```
      @foreach(var i in Model)
      {
          <li>@i.Description <a asp-action="delete" asp-route-id="@i.Id">delete</a></li>
      }
  ```
  - should also accept a type of `WishList.Models.Item` <br />
  ```
      @foreach (WishList.Models.Item item in Model)
      {
          <li>@item.Description <a asp-action="delete" asp-route-id="@item.Id">delete</a></li>
      }
   ```
   - Accepts Item, but this isn't correct; needs to be fully qualified given the existing code
   - _minor probably_  tough to address, but
     - I had the above commented out in the loop, and the tests failed locally as the got confused by the comments.
     - moving them to the top of the file allowed them to pass locally, but not via Check my work (https://github.com/snychka/AspNetCore-WishList/commit/5c96e32f4204998ef2edd418f0a9e52390f016c1)
- *6.2 Create ItemController's Index Action*
  - allow this, and variations thereof:
  ```
        public IActionResult Index()
        {
            return View("Index", _context.Items.ToList<Item>());
        }
   ```
<a name="6.6"></a>
- *6.6 Create ItemController's Delete Action*
   - **more important** change `Id` :arrow_right: `id`
   - _probably minor_ allow for `=> id == item.Id` in `FirstOrDefault`'s lambda
   - _tough_: ignore any comments; got confused when I had commented out attempts that were similar

**Comment by EricJFisher** [comment]
I forgot to close this after making the changes... my bad.
