### ISSUE TITLE
StringLength vs MaxLength mismatch

### ISSUE THREAD

**Issue by c0shea** [pluralsight-projects/AspNetCore-WishList#40]
The README says the `Description` property in `Item.cs` should use the `StringLength` attribute, but the `CreateItemModelTest` test is expecting the `MaxLength` attribute. Which one is correct?

**Comment by EricJFisher** [comment]
Sorry for the delay on correcting this issue, I've corrected the instructions to properly ask you to use `MaxLength` technically both `StringLength` and `MaxLength` are correct in the real world sense as they can both limit the permitted string length. (but the test is watching for `MaxLength`) thank you for reporting, sorry I failed to notice the issue reported here until now.
