### ISSUE TITLE
Solution to module 2 does not match the steps posted in Pluralsight project Tasks 2 and 3

### ISSUE THREAD

**Issue by kyrvlasiuk** [pluralsight-projects/AspNetCore-WishList#64]
# Project:  Build a Wishlist Application with ASP.NET Core
## Module 2: Add Middleware/Configuration to Startup.cs
![Screenshot 2020-10-21 074042](https://user-images.githubusercontent.com/42720377/96736275-4bddee80-1371-11eb-80b4-141a6b0e3c01.png)

The solution to module 2 should use:
```c#
app.UseRouting();
app.UseEndpoints(endpoints => { endpoints.MapDefaultControllerRoute(); });
```
Instead of 
```c#
app.UseMvcWithDefaultRoute();
```

Pluralsight projects showed unstable behavior. It did not at first accept correct solution, that uses endpoint routing. Stating that solution haven't had calls to _app.UseRouting_ and _app.UseEndpoints_. 

Compare solutions feature shows solution to _Module 2: Add Middleware/Configuration to Startup.cs_ from [module1-solution](/pluralsight-projects/AspNetCore-WishList/tree/module1-solution) #49

**Comment by EricJFisher** [comment]
I've merged in the fix you've provided, thank you so much for taking the time to identify, document, and submit a pull request to fix this mistake!
